<?php

declare(strict_types=1);

namespace Hestia\WebApp\Installers\Gibbon;

use Hestia\WebApp\BaseSetup;
use Hestia\WebApp\InstallationTarget\InstallationTarget;

class GibbonSetup extends BaseSetup
{
    protected array $info = [
        'name' => 'Gibbon',
        'group' => 'cms',
        'version' => '30.0.01',
        'thumbnail' => 'gibbon-logo.svg',
    ];

    protected array $config = [
        'form' => [
            "title" => [
                "type" => "select",
                "options" => ["Ms.", "Miss", "Mr.", "Mrs.", "Dr.", "Prof."],
            ],
            'surname' => 'text',
            'first_name' => 'text',
            'email' => 'text',
            'receive_support?' => [
                "type" => "select",
                "value" => "Yes",
                "options" => [ "Yes", "No"],
            ],
            'username' => 'text',
            'password' => 'password',
            'system_name' => ['value' => 'Gibbon'],
            'install_type' => [
                "type" => "select",
                "value" => "Testing",
                "options" => [ "Testing", "Production", "Development"],
            ],
            'collect_basic_stats?' => [
                "type" => "select",
                "value" => "Yes",
                "options" => [ "Yes", "No"],
            ],
            'organization_name' => 'text',
            'organization_initials' => 'text',
            "country" => [
                "type" => "select",
                "options" => [
                    "Afghanistan",
                    "Albania",
                    "Algeria",
                    "American Samoa",
                    "Andorra",
                    "Angola",
                    "Anguilla",
                    "Antarctica",
                    "Antigua and Barbuda",
                    "Argentina",
                    "Armenia",
                    "Aruba",
                    "Australia",
                    "Austria",
                    "Azerbaijan",
                    "Bahamas",
                    "Bahrain",
                    "Bangladesh",
                    "Barbados",
                    "Belarus",
                    "Belgium",
                    "Belize",
                    "Benin",
                    "Bermuda",
                    "Bhutan",
                    "Bolivia",
                    "Bosnia and Herzegovina",
                    "Botswana",
                    "Bouvet Island",
                    "Brazil",
                    "British Indian Ocean Territory",
                    "Brunei Darussalam",
                    "Bulgaria",
                    "Burkina Faso",
                    "Burundi",
                    "Cambodia",
                    "Cameroon",
                    "Canada",
                    "Cape Verde",
                    "Cayman Islands",
                    "Central African Republic",
                    "Chad",
                    "Chile",
                    "China",
                    "Christmas Island",
                    "Cocos (Keeling) Islands",
                    "Colombia",
                    "Comoros",
                    "Congo",
                    "Congo, the Democratic Republic of the",
                    "Cook Islands",
                    "Costa Rica",
                    "Croatia",
                    "Cuba",
                    "Cyprus",
                    "Czech Republic",
                    "Denmark",
                    "Djibouti",
                    "Dominica",
                    "Dominican Republic",
                    "Ecuador",
                    "Egypt",
                    "El Salvador",
                    "Equatorial Guinea",
                    "Eritrea",
                    "Estonia",
                    "Ethiopia",
                    "Falkland Islands (Malvinas)",
                    "Faroe Islands",
                    "Fiji",
                    "Finland",
                    "France",
                    "French Guiana",
                    "French Polynesia",
                    "French Southern Territories",
                    "Gabon",
                    "Gambia",
                    "Georgia",
                    "Germany",
                    "Ghana",
                    "Gibraltar",
                    "Greece",
                    "Greenland",
                    "Grenada",
                    "Guadeloupe",
                    "Guam",
                    "Guatemala",
                    "Guinea",
                    "Guinea-Bissau",
                    "Guyana",
                    "Haiti",
                    "Heard Island and Mcdonald Islands",
                    "Holy See (Vatican City State)",
                    "Honduras",
                    "Hong Kong",
                    "Hungary",
                    "Iceland",
                    "India",
                    "Indonesia",
                    "Iran, Islamic Republic of",
                    "Iraq",
                    "Ireland",
                    "Israel",
                    "Italy",
                    "Ivory Coast (Côte d'Ivoire)",
                    "Jamaica",
                    "Japan",
                    "Jordan",
                    "Kazakhstan",
                    "Kenya",
                    "Kiribati",
                    "Korea, Democratic People's Republic of",
                    "Korea, Republic of",
                    "Kuwait",
                    "Kyrgyzstan",
                    "Lao People's Democratic Republic",
                    "Latvia",
                    "Lebanon",
                    "Lesotho",
                    "Liberia",
                    "Libya",
                    "Liechtenstein",
                    "Lithuania",
                    "Luxembourg",
                    "Macao",
                    "Macedonia, the Former Yugoslav Republic of",
                    "Madagascar",
                    "Malawi",
                    "Malaysia",
                    "Maldives",
                    "Mali",
                    "Malta",
                    "Marshall Islands",
                    "Martinique",
                    "Mauritania",
                    "Mauritius",
                    "Mayotte",
                    "Mexico",
                    "Micronesia, Federated States of",
                    "Moldova, Republic of",
                    "Monaco",
                    "Mongolia",
                    "Montenegro",
                    "Montserrat",
                    "Morocco",
                    "Mozambique",
                    "Myanmar",
                    "Namibia",
                    "Nauru",
                    "Nepal",
                    "Netherlands",
                    "Netherlands Antilles",
                    "New Caledonia",
                    "New Zealand",
                    "Nicaragua",
                    "Niger",
                    "Nigeria",
                    "Niue",
                    "Norfolk Island",
                    "Northern Mariana Islands",
                    "Norway",
                    "Oman",
                    "Pakistan",
                    "Palau",
                    "Palestinian Territory, Occupied",
                    "Panama",
                    "Papua New Guinea",
                    "Paraguay",
                    "Peru",
                    "Philippines",
                    "Pitcairn",
                    "Poland",
                    "Portugal",
                    "Puerto Rico",
                    "Qatar",
                    "Reunion",
                    "Romania",
                    "Russia",
                    "Rwanda",
                    "Saint Helena",
                    "Saint Kitts and Nevis",
                    "Saint Lucia",
                    "Saint Pierre and Miquelon",
                    "Saint Vincent and the Grenadines",
                    "Samoa",
                    "San Marino",
                    "Sao Tome and Principe",
                    "Saudi Arabia",
                    "Senegal",
                    "Serbia, Republic of",
                    "Seychelles",
                    "Sierra Leone",
                    "Singapore",
                    "Slovakia",
                    "Slovenia",
                    "Solomon Islands",
                    "Somalia",
                    "South Africa",
                    "South Georgia and the South Sandwich Islands",
                    "South Sudan",
                    "Spain",
                    "Sri Lanka",
                    "Sudan",
                    "Suriname",
                    "Svalbard and Jan Mayen",
                    "Swaziland",
                    "Sweden",
                    "Switzerland",
                    "Syrian Arab Republic",
                    "Taiwan",
                    "Tajikistan",
                    "Tanzania, United Republic of",
                    "Thailand",
                    "Timor-Leste",
                    "Togo",
                    "Tokelau",
                    "Tonga",
                    "Trinidad and Tobago",
                    "Tunisia",
                    "Turkey",
                    "Turkmenistan",
                    "Turks and Caicos Islands",
                    "Tuvalu",
                    "Uganda",
                    "Ukraine",
                    "United Arab Emirates",
                    "United Kingdom",
                    "United States",
                    "United States Minor Outlying Islands",
                    "Uruguay",
                    "Uzbekistan",
                    "Vanuatu",
                    "Venezuela",
                    "Vietnam",
                    "Virgin Islands, British",
                    "Virgin Islands, U.s.",
                    "Wallis and Futuna",
                    "Western Sahara",
                    "Yemen",
                    "Zambia",
                    "Zimbabwe",
                ],
            ],
            "language" => [
                "type" => "select",
                "value" => "en_GB",
                "options" => [
                    "af_ZA" => "Afrikaans - Suid-Afrika",
                    "nl_NL" => "Dutch - Nederland",
                    "en_GB" => "English - United Kingdom",
                    "en_US" => "English - United States",
                    "es_ES" => "Español",
                    "fr_FR" => "Français - France",
                    "he_IL" => "עברית - ישראל",
                    "hr_HR" => "Hrvatski - Hrvatska",
                    "it_IT" => "Italiano - Italia",
                    "pl_PL" => "Język polski - Polska",
                    "pt_BR" => "Português - Brasil",
                    "ro_RO" => "Română",
                    "sq_AL" => "Shqip - Shqipëri",
                    "vi_VN" => "Tiếng Việt - Việt Nam",
                    "tr_TR" => "Türkçe - Türkiye",
                    "ar_SA" => "العربية - المملكة العربية السعودية",
                    "th_TH" => "ภาษาไทย - ประเทศไทย",
                    "uk_UA" => "українська мова - Україна",
                    "ur_PK" => "پاکستان - اُردُو",
                    "zh_CN" => "汉语 - 中国",
                    "zh_HK" => "繁體字 - 香港",
                ],
            ],
            "timezone" => [
                "type" => "select",
                "options" => [
                    "Africa/Abidjan",
                    "Africa/Accra",
                    "Africa/Addis_Ababa",
                    "Africa/Algiers",
                    "Africa/Asmara",
                    "Africa/Bamako",
                    "Africa/Bangui",
                    "Africa/Banjul",
                    "Africa/Bissau",
                    "Africa/Blantyre",
                    "Africa/Brazzaville",
                    "Africa/Bujumbura",
                    "Africa/Cairo",
                    "Africa/Casablanca",
                    "Africa/Ceuta",
                    "Africa/Conakry",
                    "Africa/Dakar",
                    "Africa/Dar_es_Salaam",
                    "Africa/Djibouti",
                    "Africa/Douala",
                    "Africa/El_Aaiun",
                    "Africa/Freetown",
                    "Africa/Gaborone",
                    "Africa/Harare",
                    "Africa/Johannesburg",
                    "Africa/Juba",
                    "Africa/Kampala",
                    "Africa/Khartoum",
                    "Africa/Kigali",
                    "Africa/Kinshasa",
                    "Africa/Lagos",
                    "Africa/Libreville",
                    "Africa/Lome",
                    "Africa/Luanda",
                    "Africa/Lubumbashi",
                    "Africa/Lusaka",
                    "Africa/Malabo",
                    "Africa/Maputo",
                    "Africa/Maseru",
                    "Africa/Mbabane",
                    "Africa/Mogadishu",
                    "Africa/Monrovia",
                    "Africa/Nairobi",
                    "Africa/Ndjamena",
                    "Africa/Niamey",
                    "Africa/Nouakchott",
                    "Africa/Ouagadougou",
                    "Africa/Porto-Novo",
                    "Africa/Sao_Tome",
                    "Africa/Tripoli",
                    "Africa/Tunis",
                    "Africa/Windhoek",
                    "America/Adak",
                    "America/Anchorage",
                    "America/Anguilla",
                    "America/Antigua",
                    "America/Araguaina",
                    "America/Argentina/Buenos_Aires",
                    "America/Argentina/Catamarca",
                    "America/Argentina/Cordoba",
                    "America/Argentina/Jujuy",
                    "America/Argentina/La_Rioja",
                    "America/Argentina/Mendoza",
                    "America/Argentina/Rio_Gallegos",
                    "America/Argentina/Salta",
                    "America/Argentina/San_Juan",
                    "America/Argentina/San_Luis",
                    "America/Argentina/Tucuman",
                    "America/Argentina/Ushuaia",
                    "America/Aruba",
                    "America/Asuncion",
                    "America/Atikokan",
                    "America/Bahia",
                    "America/Bahia_Banderas",
                    "America/Barbados",
                    "America/Belem",
                    "America/Belize",
                    "America/Blanc-Sablon",
                    "America/Boa_Vista",
                    "America/Bogota",
                    "America/Boise",
                    "America/Cambridge_Bay",
                    "America/Campo_Grande",
                    "America/Cancun",
                    "America/Caracas",
                    "America/Cayenne",
                    "America/Cayman",
                    "America/Chicago",
                    "America/Chihuahua",
                    "America/Ciudad_Juarez",
                    "America/Costa_Rica",
                    "America/Coyhaique",
                    "America/Creston",
                    "America/Cuiaba",
                    "America/Curacao",
                    "America/Danmarkshavn",
                    "America/Dawson",
                    "America/Dawson_Creek",
                    "America/Denver",
                    "America/Detroit",
                    "America/Dominica",
                    "America/Edmonton",
                    "America/Eirunepe",
                    "America/El_Salvador",
                    "America/Fort_Nelson",
                    "America/Fortaleza",
                    "America/Glace_Bay",
                    "America/Goose_Bay",
                    "America/Grand_Turk",
                    "America/Grenada",
                    "America/Guadeloupe",
                    "America/Guatemala",
                    "America/Guayaquil",
                    "America/Guyana",
                    "America/Halifax",
                    "America/Havana",
                    "America/Hermosillo",
                    "America/Indiana/Indianapolis",
                    "America/Indiana/Knox",
                    "America/Indiana/Marengo",
                    "America/Indiana/Petersburg",
                    "America/Indiana/Tell_City",
                    "America/Indiana/Vevay",
                    "America/Indiana/Vincennes",
                    "America/Indiana/Winamac",
                    "America/Inuvik",
                    "America/Iqaluit",
                    "America/Jamaica",
                    "America/Juneau",
                    "America/Kentucky/Louisville",
                    "America/Kentucky/Monticello",
                    "America/Kralendijk",
                    "America/La_Paz",
                    "America/Lima",
                    "America/Los_Angeles",
                    "America/Lower_Princes",
                    "America/Maceio",
                    "America/Managua",
                    "America/Manaus",
                    "America/Marigot",
                    "America/Martinique",
                    "America/Matamoros",
                    "America/Mazatlan",
                    "America/Menominee",
                    "America/Merida",
                    "America/Metlakatla",
                    "America/Mexico_City",
                    "America/Miquelon",
                    "America/Moncton",
                    "America/Monterrey",
                    "America/Montevideo",
                    "America/Montserrat",
                    "America/Nassau",
                    "America/New_York",
                    "America/Nome",
                    "America/Noronha",
                    "America/North_Dakota/Beulah",
                    "America/North_Dakota/Center",
                    "America/North_Dakota/New_Salem",
                    "America/Nuuk",
                    "America/Ojinaga",
                    "America/Panama",
                    "America/Paramaribo",
                    "America/Phoenix",
                    "America/Port-au-Prince",
                    "America/Port_of_Spain",
                    "America/Porto_Velho",
                    "America/Puerto_Rico",
                    "America/Punta_Arenas",
                    "America/Rankin_Inlet",
                    "America/Recife",
                    "America/Regina",
                    "America/Resolute",
                    "America/Rio_Branco",
                    "America/Santarem",
                    "America/Santiago",
                    "America/Santo_Domingo",
                    "America/Sao_Paulo",
                    "America/Scoresbysund",
                    "America/Sitka",
                    "America/St_Barthelemy",
                    "America/St_Johns",
                    "America/St_Kitts",
                    "America/St_Lucia",
                    "America/St_Thomas",
                    "America/St_Vincent",
                    "America/Swift_Current",
                    "America/Tegucigalpa",
                    "America/Thule",
                    "America/Tijuana",
                    "America/Toronto",
                    "America/Tortola",
                    "America/Vancouver",
                    "America/Whitehorse",
                    "America/Winnipeg",
                    "America/Yakutat",
                    "Antarctica/Casey",
                    "Antarctica/Davis",
                    "Antarctica/DumontDUrville",
                    "Antarctica/Macquarie",
                    "Antarctica/Mawson",
                    "Antarctica/McMurdo",
                    "Antarctica/Palmer",
                    "Antarctica/Rothera",
                    "Antarctica/Syowa",
                    "Antarctica/Troll",
                    "Antarctica/Vostok",
                    "Arctic/Longyearbyen",
                    "Asia/Aden",
                    "Asia/Almaty",
                    "Asia/Amman",
                    "Asia/Anadyr",
                    "Asia/Aqtau",
                    "Asia/Aqtobe",
                    "Asia/Ashgabat",
                    "Asia/Atyrau",
                    "Asia/Baghdad",
                    "Asia/Bahrain",
                    "Asia/Baku",
                    "Asia/Bangkok",
                    "Asia/Barnaul",
                    "Asia/Beirut",
                    "Asia/Bishkek",
                    "Asia/Brunei",
                    "Asia/Chita",
                    "Asia/Colombo",
                    "Asia/Damascus",
                    "Asia/Dhaka",
                    "Asia/Dili",
                    "Asia/Dubai",
                    "Asia/Dushanbe",
                    "Asia/Famagusta",
                    "Asia/Gaza",
                    "Asia/Hebron",
                    "Asia/Ho_Chi_Minh",
                    "Asia/Hong_Kong",
                    "Asia/Hovd",
                    "Asia/Irkutsk",
                    "Asia/Jakarta",
                    "Asia/Jayapura",
                    "Asia/Jerusalem",
                    "Asia/Kabul",
                    "Asia/Kamchatka",
                    "Asia/Karachi",
                    "Asia/Kathmandu",
                    "Asia/Khandyga",
                    "Asia/Kolkata",
                    "Asia/Krasnoyarsk",
                    "Asia/Kuala_Lumpur",
                    "Asia/Kuching",
                    "Asia/Kuwait",
                    "Asia/Macau",
                    "Asia/Magadan",
                    "Asia/Makassar",
                    "Asia/Manila",
                    "Asia/Muscat",
                    "Asia/Nicosia",
                    "Asia/Novokuznetsk",
                    "Asia/Novosibirsk",
                    "Asia/Omsk",
                    "Asia/Oral",
                    "Asia/Phnom_Penh",
                    "Asia/Pontianak",
                    "Asia/Pyongyang",
                    "Asia/Qatar",
                    "Asia/Qostanay",
                    "Asia/Qyzylorda",
                    "Asia/Riyadh",
                    "Asia/Sakhalin",
                    "Asia/Samarkand",
                    "Asia/Seoul",
                    "Asia/Shanghai",
                    "Asia/Singapore",
                    "Asia/Srednekolymsk",
                    "Asia/Taipei",
                    "Asia/Tashkent",
                    "Asia/Tbilisi",
                    "Asia/Tehran",
                    "Asia/Thimphu",
                    "Asia/Tokyo",
                    "Asia/Tomsk",
                    "Asia/Ulaanbaatar",
                    "Asia/Urumqi",
                    "Asia/Ust-Nera",
                    "Asia/Vientiane",
                    "Asia/Vladivostok",
                    "Asia/Yakutsk",
                    "Asia/Yangon",
                    "Asia/Yekaterinburg",
                    "Asia/Yerevan",
                    "Atlantic/Azores",
                    "Atlantic/Bermuda",
                    "Atlantic/Canary",
                    "Atlantic/Cape_Verde",
                    "Atlantic/Faroe",
                    "Atlantic/Madeira",
                    "Atlantic/Reykjavik",
                    "Atlantic/South_Georgia",
                    "Atlantic/St_Helena",
                    "Atlantic/Stanley",
                    "Australia/Adelaide",
                    "Australia/Brisbane",
                    "Australia/Broken_Hill",
                    "Australia/Darwin",
                    "Australia/Eucla",
                    "Australia/Hobart",
                    "Australia/Lindeman",
                    "Australia/Lord_Howe",
                    "Australia/Melbourne",
                    "Australia/Perth",
                    "Australia/Sydney",
                    "Europe/Amsterdam",
                    "Europe/Andorra",
                    "Europe/Astrakhan",
                    "Europe/Athens",
                    "Europe/Belgrade",
                    "Europe/Berlin",
                    "Europe/Bratislava",
                    "Europe/Brussels",
                    "Europe/Bucharest",
                    "Europe/Budapest",
                    "Europe/Busingen",
                    "Europe/Chisinau",
                    "Europe/Copenhagen",
                    "Europe/Dublin",
                    "Europe/Gibraltar",
                    "Europe/Guernsey",
                    "Europe/Helsinki",
                    "Europe/Isle_of_Man",
                    "Europe/Istanbul",
                    "Europe/Jersey",
                    "Europe/Kaliningrad",
                    "Europe/Kirov",
                    "Europe/Kyiv",
                    "Europe/Lisbon",
                    "Europe/Ljubljana",
                    "Europe/London",
                    "Europe/Luxembourg",
                    "Europe/Madrid",
                    "Europe/Malta",
                    "Europe/Mariehamn",
                    "Europe/Minsk",
                    "Europe/Monaco",
                    "Europe/Moscow",
                    "Europe/Oslo",
                    "Europe/Paris",
                    "Europe/Podgorica",
                    "Europe/Prague",
                    "Europe/Riga",
                    "Europe/Rome",
                    "Europe/Samara",
                    "Europe/San_Marino",
                    "Europe/Sarajevo",
                    "Europe/Saratov",
                    "Europe/Simferopol",
                    "Europe/Skopje",
                    "Europe/Sofia",
                    "Europe/Stockholm",
                    "Europe/Tallinn",
                    "Europe/Tirane",
                    "Europe/Ulyanovsk",
                    "Europe/Vaduz",
                    "Europe/Vatican",
                    "Europe/Vienna",
                    "Europe/Vilnius",
                    "Europe/Volgograd",
                    "Europe/Warsaw",
                    "Europe/Zagreb",
                    "Europe/Zurich",
                    "Indian/Antananarivo",
                    "Indian/Chagos",
                    "Indian/Christmas",
                    "Indian/Cocos",
                    "Indian/Comoro",
                    "Indian/Kerguelen",
                    "Indian/Mahe",
                    "Indian/Maldives",
                    "Indian/Mauritius",
                    "Indian/Mayotte",
                    "Indian/Reunion",
                    "Pacific/Apia",
                    "Pacific/Auckland",
                    "Pacific/Bougainville",
                    "Pacific/Chatham",
                    "Pacific/Chuuk",
                    "Pacific/Easter",
                    "Pacific/Efate",
                    "Pacific/Fakaofo",
                    "Pacific/Fiji",
                    "Pacific/Funafuti",
                    "Pacific/Galapagos",
                    "Pacific/Gambier",
                    "Pacific/Guadalcanal",
                    "Pacific/Guam",
                    "Pacific/Honolulu",
                    "Pacific/Kanton",
                    "Pacific/Kiritimati",
                    "Pacific/Kosrae",
                    "Pacific/Kwajalein",
                    "Pacific/Majuro",
                    "Pacific/Marquesas",
                    "Pacific/Midway",
                    "Pacific/Nauru",
                    "Pacific/Niue",
                    "Pacific/Norfolk",
                    "Pacific/Noumea",
                    "Pacific/Pago_Pago",
                    "Pacific/Palau",
                    "Pacific/Pitcairn",
                    "Pacific/Pohnpei",
                    "Pacific/Port_Moresby",
                    "Pacific/Rarotonga",
                    "Pacific/Saipan",
                    "Pacific/Tahiti",
                    "Pacific/Tarawa",
                    "Pacific/Tongatapu",
                    "Pacific/Wake",
                    "Pacific/Wallis",
                    "UTC",
                ],
            ],
            "currency" => [
                "type" => "select",
                "options" => [
                    "ARS $" => "Argentine Peso (ARS$)",
                    "AUD $" => "Australian Dollar (A$)",
                    "BRL R$" => "Brazilian Real (R$)",
                    "GBP £" => "British Pound (£)",
                    "CAD $" => "Canadian Dollar (C$)",
                    "CZK Kč" => "Czech Koruna (Kč)",
                    "DKK kr" => "Danish Krone (kr)",
                    "DOP $" => "Dominican Peso ($)",
                    "EUR €" => "Euro (€)",
                    "HKD $" => "Hong Kong Dollar ($)",
                    "HUF Ft" => "Hungarian Forint (Ft)",
                    "ILS ₪" => "Israeli New Shekel (₪)",
                    "JPY ¥" => "Japanese Yen (¥)",
                    "MYR RM" => "Malaysian Ringgit (RM)",
                    "MXN $" => "Mexican Peso ($)",
                    "TWD $" => "New Taiwan Dollar ($)",
                    "NZD $" => "New Zealand Dollar ($)",
                    "NOK kr" => "Norwegian Krone (kr)",
                    "PHP ₱" => "Philippine Peso (₱)",
                    "PLN zł" => "Polish Zloty (zł)",
                    "SGD $" => "Singapore Dollar ($)",
                    "SEK kr" => "Swedish Krona (kr)",
                    "CHF" => "Swiss Franc (CHF)",
                    "THB ฿" => "Thai Baht (฿)",
                    "USD $" => "U.S. Dollar ($)",
                    "ALL L" => "Albanian Lek (L)",
                    "DZD دج" => "Algerian Dinar (دج)",
                    "BDT ó" => "Bangladeshi Taka (ó)",
                    "BTC" => "Bitcoin",
                    "BWP P" => "Botswana Pula (P)",
                    "BGN лв." => "Bulgarian Lev (лв.)",
                    "XAF FCFA" => "Central African Francs (FCFA)",
                    "CLP $" => "Chilean Peso ($)",
                    "CNY ¥" => "Chinese Renminbi (¥)",
                    "COP $" => "Colombian Peso ($)",
                    "EGP £" => "Egyptian Pound (£)",
                    "FJD $" => "Fijian Dollar ($)",
                    "GHS GH₵" => "Ghanaian Cedi (GH₵)",
                    "GTQ Q" => "Guatemalan Quetzal (Q)",
                    "INR ₹" => "Indian Rupee₹ (₹)",
                    "IDR Rp" => "Indonesian Rupiah (Rp)",
                    "JMD $" => "Jamaican Dollar ($)",
                    "KES KSh" => "Kenyan Shilling (KSh)",
                    "LYD د.ل" => "Libyan Dinar (د.ل)",
                    "MOP" => "Macanese Pataca (MOP)",
                    "MGA" => "Malagasy Ariary (Ar)",
                    "MWK" => "Malawian Kwacha (MWK)",
                    "MVR Rf" => "Maldivian Rufiyaa (Rf)",
                    "MMK K" => "Myanmar Kyat (K)",
                    "MZN MT" => "Mozambique Metical (MT)",
                    "MAD" => "Moroccan Dirham (MAD)",
                    "NAD N$" => "Namibian Dollar (N$)",
                    "NPR ₨" => "Nepalese Rupee (₨)",
                    "NIO C$" => "Nicaraguan Córdoba (C$)",
                    "NGN ₦" => "Nigerian Naira (₦)",
                    "OMR ر.ع." => "Omani Rial (ر.ع.)",
                    "PKR ₨" => "Pakistani Rupee (₨)",
                    "RON L" => "Romanian Leu (L)",
                    "RUB ₽" => "Russian Ruble (₽)",
                    "SAR ﷼" => "Saudi Riyal (﷼)",
                    "ZAR R" => "South African Rand (R)",
                    "LKR Rs" => "Sri Lankan Rupee (Rs)",
                    "TZS TSh" => "Tanzania Shilling (TSh)",
                    "TTD $" => "Trinidad & Tobago Dollar (TTD)",
                    "TRY ₺" => "Turkish Lira (₺)",
                    "UAH ₴" => "Українська гривня (₴)",
                    "UGX USh" => "Uganda Shilling (USh)",
                    "AED د.إ" => "United Arab Emirates Dirham (د.إ)",
                    "VND ₫" => "Vietnamese Dong (₫)",
                    "XCD $" => "Eastern Caribbean Dollars ($)",
                    "XOF FCFA" => "West African Francs (FCFA)",
                    "ZMW ZK" => "Zambian Kwacha (ZMW)",
                    "ZWL $" => "Zimbabwean Dollar (ZWL $)",
                ],
            ],
            "install_demo_data?" => [
                "type" => "select",
                "value" => "No",
                "options" => [ "Yes", "No"]
            ],
        ],
        'database' => true,
        'resources' => [
            'archive' => [
                'src' => 'https://github.com/GibbonEdu/core/releases/download/v30.0.01/GibbonEduCore-InstallBundle.zip',
            ],
        ],
        'server' => [
            'nginx' => [
                'template' => 'default',
            ],
            'php' => [
                'supported' => ['8.0', '8.1', '8.2', '8.3'],
            ],
        ],
    ];

    protected function setupApplication(InstallationTarget $target, array $options): void
    {
        $this->appcontext->createFile(
            $target->getDocRoot('.htaccess'),
            file_get_contents(__DIR__ . '/.htaccess'),
        );

        $this->appcontext->sendPostRequest($target->getUrl() . "/installer/install.php?step=1", [
            "code" => $options["language"],
        ]);

        $this->appcontext->sendPostRequest($target->getUrl() . "/installer/install.php?step=2", [
            'databaseServer' => $target->database->host,
            'databaseName' => $target->database->name,
            'databaseUsername' => $target->database->user,
            'databasePassword' => $target->database->password,
            'demoData' => $options['install_demo_data?'] === "No" ? "N" : "Y",
        ]);

        $this->appcontext->sendPostRequest($target->getUrl() . "/installer/install.php?step=3", [
            'title' => $options['title'],
            'surname' => $options['surname'],
            'firstName' => $options['first_name'],
            'email' => $options['email'],
            'support' => $options['receive_support?'],
            'username' => $options['username'],
            'passwordNew' => $options['password'],
            'passwordConfirm' => $options['password'],
            'systemName' => $options['system_name'],
            'installType' => $options['install_type'],
            'statsCollection' => $options['collect_basic_stats?'] === "Yes" ? "Y" : "N",
            'organisationName' => $options['organization_name'],
            'organisationNameShort' => $options['organization_initials'],
            'country' => $options['country'],
            'currency' => $options['currency'],
            'timezone' => $options['timezone'],
        ]);

         $this->appcontext->sendPostRequest($target->getUrl() . "/installer/install.php?step=4", [
            
        ]);
    }
}